version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/site.conf
      - ./:/app
    ports:
      - 80:80